name: "[Dispatch] Release"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'branch를 입력해주세요(master와 release-x.y.z만 허용)'
        required: true
        default: 'master'
      version:
        description: 'version을 입력해주세요(x.y.z)'
        required: true
        default: '1.0.0'
      beginning:
        description: 'release의 첫 시작인 경우 true를 넣어주세요'
        required: false

env:
  BRANCH: ${{ github.event.inputs.branch }}
  VERSION: ${{ github.event.inputs.version }}
  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

jobs:
  update_base_image:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.beginning }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: Update base image version in Dockerfile
        run: |
          sed -i 's/FROM cloudforet/python-core:.+$/FROM cloudforet/python-core:${{ env.VERSION }}/' Dockerfile

      - name: Push artifacts to origin master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "CI: Update version of base image in Dockerfile"
          commit_user_name: cloudforet-admin
          commit_user_email: admin@cloudforet.io
          commit_author: cloudforet-admin <admin@cloudforet.io>
          push_options: '--force'

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "docker"

  tagging:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}
          token: ${{ secrets.PAT_TOKEN }}

      - name: tagging
        run: |
          git config user.email admin@GJ-playgroud.com
          git config user.name GJ-playgroud-admin
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

  scan:
    needs: docker
    runs-on: ubuntu-20.04
    steps:
      - name: Run Trivy vulnerability scanner
        id: trivy-scan
        run: echo "scan"

  notification:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Slack
        if: always()
        run: echo "noti"